### ISSUE TITLE
Missing information: Which DwC terms would 'arrive' to the OBIS format?

### ISSUE THREAD

**Issue by meliezer** [iobis/manual#3]
Hi,
The reader has no idea which DwC terms will remain as information once harvested by OBIS, and which will remain only when the suer downloads the original DwC-A file.

Thank you.

**Comment by pieterprovoost** [comment]
@meliezer That information can be found on the data access page: https://obis.org/manual/access/. In summary we keep all fields but some are quality controlled and may be modified.

**Comment by meliezer** [comment]
Thank you @pieterprovoost
