### ISSUE TITLE
broken link for example dataset

### ISSUE THREAD

**Issue by ymgan** [iobis/manual#60]
Hello,

The link to `Examples: ENV-DATA and DNA derived data` from the specific sentence below at this page: https://manual.obis.org/data_format.html#edna-dna-derived-data-extension returns `page not found`.

> Refer to the [Examples: ENV-DATA and DNA derived data](https://manual.obis.org/examples/#example_edna) for use case examples of eDNA and DNA derived data.

Thanks a lot!!

**Comment by EliLawrence** [comment]
Fixed! Thanks
