### ISSUE TITLE
add recommended fields for DNA derived data extensions

### ISSUE THREAD

**Issue by ymgan** [iobis/manual#72]
Will be great if there is a section in the OBIS manual that shows the recommended fields for extensions (e.g. DNA derived data extension) where we want to encourage data provider to fill in because OBIS/GBIF (or others) are building tools based on these fields

Example use case:
`DNA_Sequence` field

- https://github.com/iobis/quality-taskteam/issues/36#issuecomment-1425860259
- https://github.com/iobis/quality-taskteam/issues/36#issuecomment-1428048487

**Comment by EliLawrence** [comment]
Updated Manual has recommendations for the DNA derived data extension: https://manual.obis.org/dna_data.html#dna-dervived-data
