### ISSUE TITLE
add recommendation to populate fields in child events

### ISSUE THREAD

**Issue by ymgan** [iobis/manual#73]
Currently GBIF don't inherit from parent events for occurrence data. 

If parentEvent contains lat/lon and child events leave them blank (inheritance), the occurrences associated with the child events will have empty lat/lon. These fields are not currently populated by GBIF. 

Will be great to have a section in the manual for this so that the data will be useful for both GBIF and OBIS :)

**Comment by EliLawrence** [comment]
Marking as closed now since I added a section [here](https://manual.obis.org/format_event.html#populating-parent-and-child-events) describing how OBIS and GBIF are different in parent-child inheritance and recommending to populate both when data is going to GBIF
