### ISSUE TITLE
error on page 3.5 constructing id codes

### ISSUE THREAD

**Issue by silasprincipe** [iobis/manual#75]
There is an error in the item 3.5 (https://manual-dev.obis.org/identifiers.html): the `eventID` title is not showing correctly. Probably you need to jump one line.

![image](https://github.com/iobis/manual/assets/53846571/ed9c2063-92cf-42c0-bc9e-1c7ad2ecbfc4)

**Comment by pieterprovoost** [comment]
Thanks, fixed.
