### ISSUE TITLE
list of small issues like broken links and typos

### ISSUE THREAD

**Issue by sformel-usgs** [iobis/manual#77]
Elizabeth asked me to put my feedback in one issue.  Sorry I don't have time to do a PR right now, but I can pitch in later if time is short for y'all too.

1. section 1.5 3. 
	- [x] Typo in section header: 'Frequency' should be changed to 'Frequently'
1. section 1.5.0.4
	- [x] incorrect link: What are the OBIS quality control flags?
	- [x] update to: https://manual-dev.obis.org/dataquality.html
1. section 1.5.0.6
	- [x] incorrect link: How do I contact the data provider?
	- [x] update link to: https://manual-dev.obis.org/access.html#how-to-contact-data-provider
1. section 2
	- [x] bad link format: "run a series of quality control measures"
	- [x] replace '.md' with '.html'
1. section 2.1
	- [x] bad link: "Data from OBIS is accessible in numerous ways[LINK to access section] "
	- [x] needs link
1. section 2.1: 
	- [x] bad link format: "Your dataset can be associated with a DOI"
	- [x] needs link
1. section 2.3 
	- [x] bad link format: "moved into the extendedMeasurementOrFact table"
 	- [x] needs link
1. section 2.4.1.1
 	- [x] link to "Darwin Core" lands on web page that isn't very friendly to new users (http://rs.tdwg.org/dwc/)
	- [x] replace with:  https://dwc.tdwg.org/
1. section 2.4.1.1 
      - [x] link to OBIS xsd resolves to general OBIS website: "an OBIS extension"
      - [x] needs updated link
1. section 2.4.1.3.1 
	- [x] misspelling
	- [x] correct AlphiaID to AphiaID
1. section 2.4.1.3.1 
	- [x] misspelling
	- [x] correct belowe to below 
1. Section 2.4.1.3.1 misspelling
	- [x] 'NO'should be corrected to 'ON' in "The use and definitions for additional NO signs"
1. section 2.4.1.3.3
	- [x] dissonant guidance with GBIF DNA publishing guide
	- [x] "or MachineObservation (e.g. for occurrences based on automated sensors such as DNA sequencers, image recognition etc)."
	- [x] but DNA publishing guide says use 'MaterialSample'
	- [x] also occurs in section 4.8.1 
1. section 2.4.2.2.3
	- [x] Duncan et al. (2021) resolves to ambiguous search results (or at least I was expecting a single document).
	- [x] other occurences throughout the manual
1. section 2.4.4 
	- [x] link resolves to generic page: "See more information on EML."
	- [x] need to update link
1. section 2.4.4
	- [x] link resolves to obis homepage: "Also read the guidelines on the sharing and use of data in OBIS."
	- [x] update link
1. section 4.6.1
	- [x] incorrect link: "will occur within the extendedMeasurementOrFact extension."
	- [x] need to update link
1. section 4.8.2.1
	- [x] broken link: "The Data Carpentries have produced this exercise"
	- [x] need to update link
1. section 4.8.4.2.3
	- [x] duplication of the word 'here'
1. section 4.9.1.2.1
	- [x] broken link due to domain change: “18S Monterey Bay Time Series: an eDNA data set from Monterey Bay, California, including years 2006, 2013 - 2016
	- [x] update to: https://ipt-obis.gbif.us/resource?r=18s_monterey_bay_time_series_edna
1. section 4.9.1.3.2
	- [x] subsection 'content' seems like it's just links to the next three subesctions? Not sure of it's function. 
1. section 5.3 
	- [x] broken link: "As you are following the guidelines in this manual to format data"
	- [x] need to update link
1. section 5.4 
	- [x] bad link format: "this MoF statistics report https://r.obis.org/mof/""
	- [x] remove " from link
1. section 5.6.2 
	- [x] bad link format: For information on how to use this tool, see below.
	- [x] need to update link
1. section 6.2.3.
	- [x] in several places there are links to the outdated manual wiki
	- [x] update IPT manual link to: https://ipt.gbif.org/manual/

**Comment by silasprincipe** [comment]
Adding to the list, on section 2.4.1.3.2 Occurrence, the final example table is not rendering:

![image](https://github.com/iobis/manual/assets/53846571/097212ab-4a7d-49f2-becb-6e9c36837bb6)
