### ISSUE TITLE
Change scientificName recommendation

### ISSUE THREAD

**Issue by pieterprovoost** [iobis/manual#85]
As we have received no comments on the suggestion at https://github.com/iobis/obis-issues/issues/212, align the recommendation for `scientificName` with https://dwc.tdwg.org/list/#dwc_scientificName.

**Comment by ymgan** [comment]
Thank you so much @pieterprovoost !! will this change also be reflected in the OBIS2023EN course?

**Comment by EliLawrence** [comment]
I've updated the OBIS Manual https://manual.obis.org/darwin_core.html#taxonomy-and-identification and the OBIS OTGA course so that they both align to https://dwc.tdwg.org/list/#dwc_scientificName. Let me know if any further changes are needed, otherwise I will close this issue :)
