### ISSUE TITLE
Depth Figure (section 2.4.1.3.4)

### ISSUE THREAD

**Issue by timvdstap** [iobis/manual#94]
In the depth figure (section 2.4.1.3.4 in the OBIS Manual): looking at scenario 4 - should the reference point be at the sea surface (elevation) level, with the top of the trawl being the minimumDepthInMeters sampled, and the bottom end of the trawl perhaps indicating the maximumDepthInMeters?

If not, could someone perhaps explain how scenario is included in the event core? Seems like there'd be 2 values for minimumDepthInMeters associated with a single event?

![image](https://github.com/iobis/manual/assets/62965116/1cfe944e-0cb0-4c24-91be-b19f5c281dfb)

**Comment by EliLawrence** [comment]
Yes you are correct Tim! The reference point should be at the sea surface. I've updated the figure now. Thanks for noticing!
