### ISSUE TITLE
rs.iobis.org namespace?

### ISSUE THREAD

**Issue by sharifX** [iobis/manual#97]
We have noticed an issue with the [GBIF documentation](https://rs.gbif.org/extension/obis/extended_measurement_or_fact_2023-08-28.xml) that points to OBIS regarding the namespace for ExtendedMeasurementOrFact. The following link in the GBIF documentation does not resolve:

http://rs.iobis.org/obis/terms/ExtendedMeasurementOrFact 

We (DiSSCo/[opends](https://github.com/DiSSCo/openDS)) are interested in using the ExtendedMeasurementOrFact extension in our data schema, but the unresolved link and unclear namespace management are creating uncertainty. We need to ensure that we are referencing the correct and maintained namespace to avoid issues in our implementation.

**Comment by pieterprovoost** [comment]
Thanks @sharifX, pending a new version of the extension using the `rs.obis.org` namespace, I'll set up a landing page and make sure the current IRIs resolve. If the namespace changes in the future I'll ensure proper redirection. I'll keep you posted.

**Comment by sharifX** [comment]
Thanks for the update and the fix. Yes, this works.
